PAPP-35200: Update documentation
splunk-soar-connectors/microsoftwindowsremotemanagement pull request #39
Opened 2024-12-17 13:23 UTC by ishans-crest

Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

## Pull Request Checklist

#### Please check if your PR fulfills the following requirements:
- [ ] Testing of all the changes has been performed (for bug fixes / features)
- [ ] The manual_readme_content.md has been reviewed and added / updated if needed (for bug fixes / features)
- [ ] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [ ] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [ ] Verify all checks are passing.
- [ ] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [ ] Do NOT submit updates to dependencies unless it fixes an issue.
## Pull Request Type

#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe):

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers),
  please document them in the `manual_readme_content.md`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `manual_readme_content.md` all methods (eg, OAuth) used to authenticate
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `manual_readme_content.md`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.

## Screenshots (if relevant)

---
Thanks for contributing!

2025-01-02 13:46 UTC, bbielinski-splunk approved these changes

2025-01-02 20:49 UTC, phantom-jacob requested changes

2025-01-02 20:49 UTC, phantom-jacob commented on manual_readme_content.md
> +- **Path to SSL certificate PEM file** - The path to the signed certificate file that is trusted by the Windows instance, in PEM format.
This sounds good to me

2025-01-02 20:49 UTC, phantom-jacob commented on manual_readme_content.md
> +- **Path to SSL key file** - The path to the key file used to generate the `cert_pem` file.
```suggestion
- **Path to SSL key file** (cert_key_pem_path) - The path to the key file used to generate the `cert_pem` file.
```

2025-01-02 20:49 UTC, phantom-jacob commented on manual_readme_content.md
> +- **Path to trusted CRT file** - The certificate of the certificate authority that signed the certificate file. This is needed only if you are using your own certificate authority.
```suggestion
- **Path to trusted CRT file** (ca_trust_path) - The certificate of the certificate authority that signed the certificate file. This is needed only if you are using your own certificate authority.
```

2025-01-03 13:00 UTC, ishans-crest commented on manual_readme_content.md
> +- **Path to SSL key file** - The path to the key file used to generate the `cert_pem` file.
Done

2025-01-03 13:01 UTC, ishans-crest commented on manual_readme_content.md
> +- **Path to trusted CRT file** - The certificate of the certificate authority that signed the certificate file. This is needed only if you are using your own certificate authority.
Done

2025-01-03 13:18 UTC, bb-splunk approved these changes

2025-01-08 09:15 UTC, jkamienski-splunk approved these changes

2025-01-08 09:41 UTC, phantom-jacob approved these changes

2025-01-08 09:53 UTC, merged